import 'server-only';
import { and, desc, eq, isNull, sql } from 'drizzle-orm';
import {
  db,
  rvmAudioAssets,
  type RvmAudioAsset,
} from '@procur/db';

/**
 * Read/write helpers for rvm_audio_assets. Used by:
 *   - Dashboard upload route (POST /api/rvm/audio-assets) when
 *     operator manually uploads OR Voicebox-generated bytes land
 *   - Autopilot RVM executor (PR 3) at dispatch time —
 *     pickActiveAudioAssetForDispatch is the single source of truth
 *     for "which audio plays for (probe, variant, language)"
 *   - Probe page audio panel (list + retire flows)
 *
 * Discipline: only one active asset per (probe, variant, language)
 * at a time (enforced by partial unique index on is_active=true).
 * Replacing an asset retires the prior one rather than deleting —
 * audit history is preserved; operator can roll back via the
 * dashboard.
 */

export type { RvmAudioAsset };

export interface CreateRvmAudioAssetInput {
  probeId: string;
  variantId?: string | null;
  language: string;
  sourceText: string;
  audioUrl: string;
  audioFormat?: string;
  durationMs?: number | null;
  voiceProfileId?: string | null;
  generatedVia:
    | 'voicebox'
    | 'manual_upload'
    | 'openai_tts'
    | 'elevenlabs'
    | 'other';
  generatedByUserId?: string | null;
}

/**
 * Create a new active audio asset, retiring any existing active
 * asset with the same scope (probe, variant, language).
 *
 * Two sequential auto-committed statements — the neon-http driver
 * doesn't support transactions (per CLAUDE.md "migration footguns").
 * Retire first, then insert: if the insert fails, the retire is
 * harmless (the operator's prior asset is just inactive and
 * recoverable via reactivateRvmAudioAsset). The reverse ordering
 * would trip the partial unique index since two active rows for the
 * same (probe, variant, language) scope can't coexist.
 *
 * Single-tenant single-operator deployment, so the brief window
 * between retire and insert isn't a concurrency concern in practice
 * — two operators uploading audio for the same scope at the same
 * second would in theory hit the partial unique index, but it's not
 * a realistic scenario.
 *
 * Operators iterating on a recording (record → preview → re-record)
 * each upload creates a new row; prior versions stay queryable via
 * is_active=false for audit + roll-back.
 */
export async function createRvmAudioAsset(
  input: CreateRvmAudioAssetInput,
): Promise<RvmAudioAsset> {
  await db
    .update(rvmAudioAssets)
    .set({ isActive: false, updatedAt: new Date() })
    .where(
      and(
        eq(rvmAudioAssets.probeId, input.probeId),
        eq(rvmAudioAssets.language, input.language),
        eq(rvmAudioAssets.isActive, true),
        input.variantId
          ? eq(rvmAudioAssets.variantId, input.variantId)
          : isNull(rvmAudioAssets.variantId),
      ),
    );

  const [created] = await db
    .insert(rvmAudioAssets)
    .values({
      probeId: input.probeId,
      variantId: input.variantId ?? null,
      language: input.language,
      sourceText: input.sourceText,
      audioUrl: input.audioUrl,
      audioFormat: input.audioFormat ?? 'audio/mpeg',
      durationMs: input.durationMs ?? null,
      voiceProfileId: input.voiceProfileId ?? null,
      generatedVia: input.generatedVia,
      generatedByUserId: input.generatedByUserId ?? null,
    })
    .returning();
  if (!created) throw new Error('createRvmAudioAsset: no row returned');
  return created;
}

export async function listRvmAudioAssetsForProbe(
  probeId: string,
  options: { activeOnly?: boolean } = {},
): Promise<RvmAudioAsset[]> {
  const filters = [eq(rvmAudioAssets.probeId, probeId)];
  if (options.activeOnly) filters.push(eq(rvmAudioAssets.isActive, true));
  return await db
    .select()
    .from(rvmAudioAssets)
    .where(and(...filters))
    .orderBy(
      desc(rvmAudioAssets.isActive),
      desc(rvmAudioAssets.generatedAt),
    );
}

/**
 * Pick the audio asset to play at dispatch time for a given probe
 * + variant + language. Variant-specific asset wins over probe-
 * default; both must be active.
 *
 * Returns null when no active asset exists for the scope —
 * caller (autopilot eligibility) skips the target with a clear
 * "no rvm audio for <lang> in probe <id>" reason.
 */
export async function pickActiveAudioAssetForDispatch(input: {
  probeId: string;
  variantId: string | null;
  language: string;
}): Promise<RvmAudioAsset | null> {
  // Try variant-specific first when variantId is set.
  if (input.variantId) {
    const [variantSpecific] = await db
      .select()
      .from(rvmAudioAssets)
      .where(
        and(
          eq(rvmAudioAssets.probeId, input.probeId),
          eq(rvmAudioAssets.variantId, input.variantId),
          eq(rvmAudioAssets.language, input.language),
          eq(rvmAudioAssets.isActive, true),
        ),
      )
      .limit(1);
    if (variantSpecific) return variantSpecific;
  }

  // Fall back to probe-default (variantId IS NULL).
  const [probeDefault] = await db
    .select()
    .from(rvmAudioAssets)
    .where(
      and(
        eq(rvmAudioAssets.probeId, input.probeId),
        isNull(rvmAudioAssets.variantId),
        eq(rvmAudioAssets.language, input.language),
        eq(rvmAudioAssets.isActive, true),
      ),
    )
    .limit(1);
  return probeDefault ?? null;
}

/**
 * Retire an asset. Preserves history; another active asset for the
 * same scope can be created afterward. Idempotent: retiring an
 * already-retired asset is a no-op.
 */
export async function retireRvmAudioAsset(assetId: string): Promise<void> {
  await db
    .update(rvmAudioAssets)
    .set({ isActive: false, updatedAt: new Date() })
    .where(eq(rvmAudioAssets.id, assetId));
}

/**
 * Reactivate a previously-retired asset. If another asset is
 * currently active for the same (probe, variant, language) scope,
 * that one gets retired first (single-active invariant preserved).
 *
 * Three sequential auto-committed statements — neon-http doesn't
 * support transactions. Lookup, retire-current-active, activate-
 * target. Same single-tenant concurrency caveat as createRvmAudioAsset.
 */
export async function reactivateRvmAudioAsset(assetId: string): Promise<void> {
  const [target] = await db
    .select()
    .from(rvmAudioAssets)
    .where(eq(rvmAudioAssets.id, assetId))
    .limit(1);
  if (!target) return;
  await db
    .update(rvmAudioAssets)
    .set({ isActive: false, updatedAt: new Date() })
    .where(
      and(
        eq(rvmAudioAssets.probeId, target.probeId),
        eq(rvmAudioAssets.language, target.language),
        eq(rvmAudioAssets.isActive, true),
        target.variantId
          ? eq(rvmAudioAssets.variantId, target.variantId)
          : isNull(rvmAudioAssets.variantId),
      ),
    );
  await db
    .update(rvmAudioAssets)
    .set({ isActive: true, updatedAt: new Date() })
    .where(eq(rvmAudioAssets.id, assetId));
}

/**
 * Has the probe got at least one active audio asset for the given
 * language? Cheap eligibility check the autopilot calls before
 * deciding whether to dispatch on the RVM channel for a probe.
 */
export async function probeHasActiveAudioForLanguage(
  probeId: string,
  language: string,
): Promise<boolean> {
  const [row] = await db
    .select({ id: rvmAudioAssets.id })
    .from(rvmAudioAssets)
    .where(
      and(
        eq(rvmAudioAssets.probeId, probeId),
        eq(rvmAudioAssets.language, language),
        eq(rvmAudioAssets.isActive, true),
      ),
    )
    .limit(1);
  return Boolean(row);
}

/** Suppresses unused-import lint when the helper file is imported
 *  for types only. */
export const __rvmAudioAssetsHelpersTouch = sql`1`;
