/**
 * Tier-1 Caribbean marine-bunker buyers per
 * docs/caribbean-fuel-buyer-brief.md §4.3.
 *
 * Caribbean ports are major bunker hubs: cruise traffic, Kingston/
 * Caucedo/Freeport/Cartagena transshipment, Panama Canal traffic
 * that bunkers in the region. Both physical bunker suppliers and
 * cruise-line corporate fuel desks (decision-makers in Miami)
 * land here.
 */
import { ingestSegmentSeed, type FuelBuyerSeedEntry, type SegmentRunSummary } from './_shared';

const SEED: FuelBuyerSeedEntry[] = [
  {
    slug: 'fuel-buyer:petrojam-bunkering',
    name: 'Petrojam Bunkering',
    country: 'JM',
    aliases: ['Petrojam Bunker'],
    // Kingston Harbour, Jamaica.
    latitude: 17.97,
    longitude: -76.85,
    notes:
      'Petrojam\'s bunkering arm at Kingston Harbour. Already in supplier rolodex on the supply side; flagged here as a buyer-side relationship for off-take of refined product surpluses.',
    profile: {
      segments: ['marine-bunker-supplier'],
      fuelTypesPurchased: ['hfo-380cst', 'hfo-180cst', 'vlsfo', 'lsmgo'],
      annualPurchaseVolumeBblMin: 1_000_000,
      annualPurchaseVolumeBblMax: 2_500_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 15_000, max: 35_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM'],
      decisionMakerCountry: 'JM',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.82,
    },
  },
  {
    slug: 'fuel-buyer:monjasa-caribbean',
    name: 'Monjasa Caribbean',
    country: 'PA',
    aliases: ['Monjasa'],
    notes:
      'Physical bunker supplier with Caribbean + Panama Canal coverage. Multi-port operations including Cristobal + Houston anchored.',
    profile: {
      segments: ['marine-bunker-supplier'],
      fuelTypesPurchased: ['hfo-380cst', 'vlsfo', 'lsmgo', 'diesel-marine-gasoil'],
      annualPurchaseVolumeBblMin: 4_000_000,
      annualPurchaseVolumeBblMax: 7_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 20_000, max: 50_000 },
      procurementModel: 'spot-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['PA', 'JM', 'BS', 'TT'],
      decisionMakerCountry: 'DK',
      paymentInstrumentCapability: ['lc-sight', 'cad', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Decision-maker country is Denmark (Monjasa HQ Fredericia).',
      confidenceScore: 0.92,
    },
  },
  {
    slug: 'fuel-buyer:wfs-caribbean',
    name: 'World Fuel Services Caribbean',
    country: 'BS',
    aliases: ['WFS', 'World Kinect Caribbean'],
    notes:
      'Bunker supply across Caribbean ports (Bahamas hub). Large global bunker operator with Caribbean physical + broker presence.',
    profile: {
      segments: ['marine-bunker-supplier', 'aviation-fuel-handler'],
      fuelTypesPurchased: ['hfo-380cst', 'vlsfo', 'lsmgo', 'jet-a-1'],
      annualPurchaseVolumeBblMin: 5_000_000,
      annualPurchaseVolumeBblMax: 10_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 25_000, max: 60_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS', 'JM', 'TT', 'PR', 'BB'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Decision-maker country is US (Miami HQ); rebranded to World Kinect.',
      confidenceScore: 0.92,
    },
  },
  {
    slug: 'fuel-buyer:borco-bahamas',
    name: 'BORCO (Buckeye Bahamas)',
    country: 'BS',
    aliases: ['Bahamas Oil Refining Company', 'Buckeye Bahamas Hub'],
    // Freeport, Grand Bahama.
    latitude: 26.52,
    longitude: -78.78,
    notes:
      'Major Bahamas terminal at Freeport. Storage + bunker capability; serves transshipment traffic. Owned by Buckeye Partners.',
    profile: {
      segments: ['marine-bunker-supplier', 'industrial-distributor'],
      fuelTypesPurchased: ['hfo-380cst', 'vlsfo', 'lsmgo', 'gasoline-87', 'diesel-ulsd'],
      annualPurchaseVolumeBblMin: 8_000_000,
      annualPurchaseVolumeBblMax: 15_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 40_000, max: 80_000 },
      procurementModel: 'spot-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Decision-maker country is US (Buckeye Partners HQ Houston).',
      confidenceScore: 0.92,
    },
  },
  {
    slug: 'fuel-buyer:statia-terminals',
    name: 'Statia Terminals',
    country: 'BQ',
    aliases: ['NuStar Statia'],
    // St. Eustatius (Sint Eustatius), Caribbean Netherlands.
    latitude: 17.49,
    longitude: -62.99,
    notes: 'St. Eustatius terminal. Major storage + bunker capability serving Caribbean transshipment.',
    profile: {
      segments: ['marine-bunker-supplier', 'industrial-distributor'],
      fuelTypesPurchased: ['hfo-380cst', 'vlsfo', 'lsmgo', 'gasoline-87', 'diesel-ulsd'],
      annualPurchaseVolumeBblMin: 5_000_000,
      annualPurchaseVolumeBblMax: 10_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-capacity',
      typicalCargoSizeMt: { min: 30_000, max: 70_000 },
      procurementModel: 'spot-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BQ'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Owned by NuStar Energy (TX).',
      confidenceScore: 0.85,
    },
  },
  {
    slug: 'fuel-buyer:curoil',
    name: 'Curoil',
    country: 'CW',
    aliases: ['Curaçao Oil Storage'],
    // Bullen Bay / Willemstad terminal complex.
    latitude: 12.18,
    longitude: -68.94,
    notes: 'Curaçao bunker supplier active at Willemstad. Pure physical bunker operator.',
    profile: {
      segments: ['marine-bunker-supplier'],
      fuelTypesPurchased: ['hfo-380cst', 'vlsfo', 'lsmgo'],
      annualPurchaseVolumeBblMin: 1_000_000,
      annualPurchaseVolumeBblMax: 2_500_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 12_000, max: 30_000 },
      procurementModel: 'spot-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['CW'],
      decisionMakerCountry: 'CW',
      paymentInstrumentCapability: ['lc-sight', 'cad', 'open-account'],
      knownBanks: [],
      ownershipType: 'private-domestic',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.78,
    },
  },
  {
    slug: 'fuel-buyer:carnival-corp-fuel',
    name: 'Carnival Corporation — Corporate Fuel Procurement',
    country: 'US',
    aliases: ['Carnival Cruise Line', 'Carnival Corp & plc'],
    notes:
      'Corporate fuel desk for the entire Carnival fleet (Carnival, Princess, Cunard, Holland America, Costa, AIDA, P&O, Seabourn). Caribbean port-calls drive substantial bunker demand. Decisions made centrally in Miami.',
    profile: {
      segments: ['hospitality-cruise-line-corporate', 'marine-cruise-line-fueling'],
      fuelTypesPurchased: ['vlsfo', 'lsmgo', 'hfo-380cst'],
      annualPurchaseVolumeBblMin: 25_000_000,
      annualPurchaseVolumeBblMax: 35_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 30_000, max: 80_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: ['Shell Marine', 'BP Marine', 'World Fuel Services'],
      caribbeanCountriesOperated: ['BS', 'JM', 'KY', 'PR', 'BB', 'AW'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: 'VP Fuel Procurement',
      primaryContactName: null,
      notes: 'NYSE: CCL. Largest cruise operator globally.',
      confidenceScore: 0.92,
    },
  },
  {
    slug: 'fuel-buyer:rcl-fuel',
    name: 'Royal Caribbean Group — Fuel Procurement',
    country: 'US',
    aliases: ['Royal Caribbean Cruises', 'RCL'],
    notes:
      'Fleet fuel desk for Royal Caribbean, Celebrity Cruises, Silversea. Significant Caribbean port-call presence. Miami HQ.',
    profile: {
      segments: ['hospitality-cruise-line-corporate', 'marine-cruise-line-fueling'],
      fuelTypesPurchased: ['vlsfo', 'lsmgo'],
      annualPurchaseVolumeBblMin: 15_000_000,
      annualPurchaseVolumeBblMax: 22_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 30_000, max: 70_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS', 'JM', 'KY', 'PR', 'BB', 'AW', 'HT'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: 'Director Fuel Procurement',
      primaryContactName: null,
      notes: 'NYSE: RCL.',
      confidenceScore: 0.92,
    },
  },
  {
    slug: 'fuel-buyer:ncl-fuel',
    name: 'Norwegian Cruise Line Holdings — Fuel Procurement',
    country: 'US',
    aliases: ['Norwegian Cruise Line', 'NCLH'],
    notes:
      'Fleet fuel desk for Norwegian, Oceania, Regent Seven Seas. Miami HQ.',
    profile: {
      segments: ['hospitality-cruise-line-corporate', 'marine-cruise-line-fueling'],
      fuelTypesPurchased: ['vlsfo', 'lsmgo'],
      annualPurchaseVolumeBblMin: 6_000_000,
      annualPurchaseVolumeBblMax: 10_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 25_000, max: 55_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS', 'JM', 'KY', 'PR', 'BB'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'NYSE: NCLH.',
      confidenceScore: 0.88,
    },
  },
];

export type MarineBunkerSeedRunSummary = SegmentRunSummary<'marine-bunker-seed'>;

export async function runFuelBuyerMarineBunkerSeed(): Promise<MarineBunkerSeedRunSummary> {
  return ingestSegmentSeed('marine-bunker-seed', SEED, 'marine-bunker');
}
