/**
 * Tier-1 Caribbean hospitality fuel buyers per
 * docs/caribbean-fuel-buyer-brief.md §4.8. Major resort operators
 * with backup generation, fuel storage, marine bunkering in some
 * cases.
 */
import { ingestSegmentSeed, type FuelBuyerSeedEntry, type SegmentRunSummary } from './_shared';

const SEED: FuelBuyerSeedEntry[] = [
  {
    slug: 'fuel-buyer:bahia-principe',
    name: 'Bahía Príncipe',
    country: 'ES',
    aliases: ['Grupo Piñero'],
    notes:
      'Major Spanish resort chain with significant Caribbean footprint (DR, JM). Backup generation + LPG cooking demand.',
    profile: {
      segments: ['hospitality-hotel-resort'],
      fuelTypesPurchased: ['diesel-ulsd', 'lpg-propane'],
      annualPurchaseVolumeBblMin: 100_000,
      annualPurchaseVolumeBblMax: 300_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 3_000, max: 8_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'regional',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO', 'JM', 'MX'],
      decisionMakerCountry: 'ES',
      paymentInstrumentCapability: ['lc-sight', 'open-account'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 3,
      primaryContactRole: 'Procurement Director',
      primaryContactName: null,
      notes: 'Owned by Grupo Piñero (ES).',
      confidenceScore: 0.65,
    },
  },
  {
    slug: 'fuel-buyer:iberostar-caribbean',
    name: 'Iberostar Caribbean',
    country: 'ES',
    notes: 'Spanish resort operator with multi-island Caribbean presence.',
    profile: {
      segments: ['hospitality-hotel-resort'],
      fuelTypesPurchased: ['diesel-ulsd', 'lpg-propane'],
      annualPurchaseVolumeBblMin: 80_000,
      annualPurchaseVolumeBblMax: 250_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 2_500, max: 7_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'regional',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO', 'JM', 'CU', 'MX'],
      decisionMakerCountry: 'ES',
      paymentInstrumentCapability: ['lc-sight', 'open-account'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.65,
    },
  },
  {
    slug: 'fuel-buyer:riu-caribbean',
    name: 'RIU Hotels — Caribbean operations',
    country: 'ES',
    aliases: ['RIU Hotels & Resorts'],
    notes: 'Spanish resort chain. Significant Cuba, DR, JM, BS presence.',
    profile: {
      segments: ['hospitality-hotel-resort'],
      fuelTypesPurchased: ['diesel-ulsd', 'lpg-propane'],
      annualPurchaseVolumeBblMin: 60_000,
      annualPurchaseVolumeBblMax: 200_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 2_000, max: 6_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'regional',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO', 'JM', 'BS', 'CU', 'MX'],
      decisionMakerCountry: 'ES',
      paymentInstrumentCapability: ['lc-sight', 'open-account'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.65,
    },
  },
  {
    slug: 'fuel-buyer:sandals-resorts',
    name: 'Sandals Resorts International',
    country: 'JM',
    aliases: ['Sandals'],
    notes:
      'Multi-island Caribbean resort chain. Each property runs backup generation; some have marine fueling for water-sports fleet.',
    profile: {
      segments: ['hospitality-hotel-resort'],
      fuelTypesPurchased: ['diesel-ulsd', 'lpg-propane', 'gasoline-87'],
      annualPurchaseVolumeBblMin: 80_000,
      annualPurchaseVolumeBblMax: 250_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 2_500, max: 7_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM', 'BS', 'BB', 'AG', 'LC', 'GD'],
      decisionMakerCountry: 'JM',
      paymentInstrumentCapability: ['lc-sight', 'open-account'],
      knownBanks: [],
      ownershipType: 'private-domestic',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:atlantis-bahamas',
    name: 'Atlantis Paradise Island',
    country: 'BS',
    aliases: ['Kerzner Atlantis'],
    notes:
      'Major Bahamas integrated resort. Significant on-property fuel infrastructure for backup generation + water park + marine.',
    profile: {
      segments: ['hospitality-hotel-resort'],
      fuelTypesPurchased: ['diesel-ulsd', 'lpg-propane', 'gasoline-87'],
      annualPurchaseVolumeBblMin: 80_000,
      annualPurchaseVolumeBblMax: 200_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 2_500, max: 6_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS'],
      decisionMakerCountry: 'BS',
      paymentInstrumentCapability: ['lc-sight', 'open-account'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.7,
    },
  },
];

export type HospitalitySeedRunSummary = SegmentRunSummary<'hospitality-seed'>;

export async function runFuelBuyerHospitalitySeed(): Promise<HospitalitySeedRunSummary> {
  return ingestSegmentSeed('hospitality-seed', SEED, 'hospitality');
}
