/**
 * Tier-1 Caribbean construction + infrastructure contractors per
 * docs/caribbean-fuel-buyer-brief.md §4.6. Large infrastructure
 * programs in DR, Jamaica, Trinidad, Bahamas, and tourism
 * expansion drive cargo-scale fuel purchases for equipment fleets.
 */
import { ingestSegmentSeed, type FuelBuyerSeedEntry, type SegmentRunSummary } from './_shared';

const SEED: FuelBuyerSeedEntry[] = [
  {
    slug: 'fuel-buyer:acciona-infraestructuras-do',
    name: 'Acciona Infraestructuras (DR)',
    country: 'DO',
    aliases: ['Acciona Construcción Caribbean'],
    notes:
      'Spanish infrastructure firm with significant DR highway + airport programs. Diesel-intensive equipment fleets.',
    profile: {
      segments: ['industrial-construction-contractor'],
      fuelTypesPurchased: ['diesel-ulsd'],
      annualPurchaseVolumeBblMin: 200_000,
      annualPurchaseVolumeBblMax: 600_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 5_000, max: 15_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'regional',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO'],
      decisionMakerCountry: 'ES',
      paymentInstrumentCapability: ['lc-sight', 'open-account'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 2,
      primaryContactRole: 'Procurement Manager',
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:ohla-caribbean',
    name: 'OHLA (formerly OHL) — Caribbean operations',
    country: 'ES',
    aliases: ['OHL Caribbean'],
    notes: 'Spanish construction firm with significant DR + Cuba (historical) work.',
    profile: {
      segments: ['industrial-construction-contractor'],
      fuelTypesPurchased: ['diesel-ulsd'],
      annualPurchaseVolumeBblMin: 150_000,
      annualPurchaseVolumeBblMax: 400_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 4_000, max: 12_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'regional',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO'],
      decisionMakerCountry: 'ES',
      paymentInstrumentCapability: ['lc-sight'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:estrella-construction-do',
    name: 'Estrella Construction',
    country: 'DO',
    aliases: ['Constructora Estrella'],
    notes:
      'Major Dominican domestic contractor. Long-running infrastructure + commercial portfolio.',
    profile: {
      segments: ['industrial-construction-contractor'],
      fuelTypesPurchased: ['diesel-ulsd'],
      annualPurchaseVolumeBblMin: 100_000,
      annualPurchaseVolumeBblMax: 350_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 3_000, max: 10_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO'],
      decisionMakerCountry: 'DO',
      paymentInstrumentCapability: ['lc-sight', 'cad'],
      knownBanks: [],
      ownershipType: 'private-domestic',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:chec-caribbean',
    name: 'CHEC (China Harbour Engineering) — Caribbean',
    country: 'CN',
    aliases: ['China Harbour Engineering Caribbean'],
    notes:
      'CCCC subsidiary running multiple Caribbean port + infrastructure programs (DR, JM, BS).',
    profile: {
      segments: ['industrial-construction-contractor'],
      fuelTypesPurchased: ['diesel-ulsd'],
      annualPurchaseVolumeBblMin: 200_000,
      annualPurchaseVolumeBblMax: 600_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 5_000, max: 15_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'regional',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM', 'BS', 'DO'],
      decisionMakerCountry: 'CN',
      paymentInstrumentCapability: ['lc-sight'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Decision-maker country is China (CCCC HQ Beijing).',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:powerchina-caribbean',
    name: 'PowerChina — Caribbean',
    country: 'CN',
    aliases: ['Sinohydro Caribbean'],
    notes: 'PowerChina subsidiary with multiple Caribbean energy + infrastructure projects.',
    profile: {
      segments: ['industrial-construction-contractor'],
      fuelTypesPurchased: ['diesel-ulsd'],
      annualPurchaseVolumeBblMin: 100_000,
      annualPurchaseVolumeBblMax: 400_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 3_000, max: 12_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'regional',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM', 'BS'],
      decisionMakerCountry: 'CN',
      paymentInstrumentCapability: ['lc-sight'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.65,
    },
  },
];

export type ConstructionSeedRunSummary = SegmentRunSummary<'construction-seed'>;

export async function runFuelBuyerConstructionSeed(): Promise<ConstructionSeedRunSummary> {
  return ingestSegmentSeed('construction-seed', SEED, 'construction');
}
