/**
 * Tier-1 Caribbean government + military fuel buyers per
 * docs/caribbean-fuel-buyer-brief.md §4.7. State-owned fuel buyers
 * outside utilities — military, public transport, public works.
 */
import { ingestSegmentSeed, type FuelBuyerSeedEntry, type SegmentRunSummary } from './_shared';

const SEED: FuelBuyerSeedEntry[] = [
  {
    slug: 'fuel-buyer:jdf',
    name: 'Jamaica Defence Force',
    country: 'JM',
    aliases: ['JDF'],
    notes: 'Jamaica military. Fuel procurement via central government tenders.',
    profile: {
      segments: ['government-military'],
      fuelTypesPurchased: ['diesel-ulsd', 'gasoline-87', 'jet-a-1'],
      annualPurchaseVolumeBblMin: 80_000,
      annualPurchaseVolumeBblMax: 200_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 2_000, max: 8_000 },
      procurementModel: 'tender-only',
      procurementAuthority: 'centralized',
      knownSuppliers: ['Petrojam'],
      caribbeanCountriesOperated: ['JM'],
      decisionMakerCountry: 'JM',
      paymentInstrumentCapability: ['open-account'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Below typical cargo-import scale; surfaces only on tendered larger packages.',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:ttdf',
    name: 'Trinidad and Tobago Defence Force',
    country: 'TT',
    aliases: ['TTDF', 'TT Defence Force'],
    notes: 'TT military. Fuel procurement via TT government tenders.',
    profile: {
      segments: ['government-military'],
      fuelTypesPurchased: ['diesel-ulsd', 'gasoline-87'],
      annualPurchaseVolumeBblMin: 60_000,
      annualPurchaseVolumeBblMax: 150_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 2_000, max: 6_000 },
      procurementModel: 'tender-only',
      procurementAuthority: 'centralized',
      knownSuppliers: ['Heritage Petroleum'],
      caribbeanCountriesOperated: ['TT'],
      decisionMakerCountry: 'TT',
      paymentInstrumentCapability: ['open-account'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:rbdf',
    name: 'Royal Bahamas Defence Force',
    country: 'BS',
    aliases: ['RBDF'],
    notes: 'Bahamas military.',
    profile: {
      segments: ['government-military'],
      fuelTypesPurchased: ['diesel-marine-gasoil', 'lsmgo', 'gasoline-87'],
      annualPurchaseVolumeBblMin: 40_000,
      annualPurchaseVolumeBblMax: 120_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 1_500, max: 5_000 },
      procurementModel: 'tender-only',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS'],
      decisionMakerCountry: 'BS',
      paymentInstrumentCapability: ['open-account'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Marine-focused fleet; bunker-grade fuels dominate.',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:jutc',
    name: 'Jamaica Urban Transit Company (JUTC)',
    country: 'JM',
    aliases: ['JUTC'],
    notes: 'Jamaica state-owned bus transit. Diesel-fleet operator.',
    profile: {
      segments: ['government-public-transport'],
      fuelTypesPurchased: ['diesel-ulsd', 'diesel-lsd'],
      annualPurchaseVolumeBblMin: 250_000,
      annualPurchaseVolumeBblMax: 450_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 6_000, max: 14_000 },
      procurementModel: 'tender-only',
      procurementAuthority: 'centralized',
      knownSuppliers: ['Petrojam'],
      caribbeanCountriesOperated: ['JM'],
      decisionMakerCountry: 'JM',
      paymentInstrumentCapability: ['open-account', 'lc-sight'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.78,
    },
  },
  {
    slug: 'fuel-buyer:do-ministerio-defensa',
    name: 'República Dominicana — Ministerio de Defensa',
    country: 'DO',
    aliases: ['DR Ministry of Defense'],
    notes:
      'DR military fuel procurement. Operates army, navy, and air force fleets.',
    profile: {
      segments: ['government-military'],
      fuelTypesPurchased: ['diesel-ulsd', 'gasoline-87', 'jet-a-1'],
      annualPurchaseVolumeBblMin: 150_000,
      annualPurchaseVolumeBblMax: 400_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 4_000, max: 12_000 },
      procurementModel: 'tender-only',
      procurementAuthority: 'centralized',
      knownSuppliers: ['REFIDOMSA'],
      caribbeanCountriesOperated: ['DO'],
      decisionMakerCountry: 'DO',
      paymentInstrumentCapability: ['open-account', 'lc-sight'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.72,
    },
  },
];

export type GovernmentSeedRunSummary = SegmentRunSummary<'government-seed'>;

export async function runFuelBuyerGovernmentSeed(): Promise<GovernmentSeedRunSummary> {
  return ingestSegmentSeed('government-seed', SEED, 'government');
}
