/**
 * Tier-1 Caribbean industrial distributors per
 * docs/caribbean-fuel-buyer-brief.md §4.5. The main alternative
 * channel to refinery-direct buying — multinational majors plus
 * regional independents importing finished product for breakdown
 * into smaller markets.
 */
import { ingestSegmentSeed, type FuelBuyerSeedEntry, type SegmentRunSummary } from './_shared';

const SEED: FuelBuyerSeedEntry[] = [
  {
    slug: 'fuel-buyer:rubis-caraibes',
    name: 'Rubis Caraïbes',
    country: 'FR',
    aliases: ['Rubis Antilles Guyane', 'Rubis Caribbean'],
    notes:
      'Major Caribbean fuel distributor (gasoline, diesel, LPG, jet) across French and Anglo Caribbean. Wide network of retail + commercial accounts.',
    profile: {
      segments: ['industrial-distributor', 'retail-distributor-network'],
      fuelTypesPurchased: ['gasoline-87', 'gasoline-90', 'diesel-ulsd', 'jet-a-1', 'lpg-propane'],
      annualPurchaseVolumeBblMin: 8_000_000,
      annualPurchaseVolumeBblMax: 14_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 25_000, max: 60_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['MQ', 'GP', 'GF', 'BB', 'DM', 'GD', 'LC', 'VC', 'AI', 'BS', 'JM', 'TT'],
      decisionMakerCountry: 'FR',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: 'Trading Director',
      primaryContactName: null,
      notes: 'Listed on Euronext Paris (RUI). Caribbean is largest segment for the group.',
      confidenceScore: 0.92,
    },
  },
  {
    slug: 'fuel-buyer:sol-petroleum',
    name: 'Sol Petroleum',
    country: 'BB',
    aliases: ['SOL', 'Sol Group'],
    notes:
      'Pan-Caribbean fuel distributor. Acquired by Parkland Corporation (Canada) but Caribbean operations retain regional decision authority.',
    profile: {
      segments: ['industrial-distributor', 'retail-distributor-network'],
      fuelTypesPurchased: ['gasoline-87', 'gasoline-90', 'diesel-ulsd', 'jet-a-1', 'hfo-380cst'],
      annualPurchaseVolumeBblMin: 12_000_000,
      annualPurchaseVolumeBblMax: 20_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 30_000, max: 70_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BB', 'JM', 'TT', 'BS', 'GY', 'BZ', 'LC', 'VC', 'GD', 'KN', 'DM'],
      decisionMakerCountry: 'BB',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: 'VP Trading',
      primaryContactName: null,
      notes: 'Subsidiary of Parkland Corporation (TSX: PKI).',
      confidenceScore: 0.92,
    },
  },
  {
    slug: 'fuel-buyer:chevron-caribbean',
    name: 'Texaco / Chevron Caribbean',
    country: 'US',
    aliases: ['Chevron Caribbean', 'Texaco Caribbean'],
    notes:
      'Caribbean retail and industrial fuel network. Multiple country footprints with branded retail.',
    profile: {
      segments: ['industrial-distributor', 'retail-distributor-network'],
      fuelTypesPurchased: ['gasoline-87', 'gasoline-90', 'diesel-ulsd', 'jet-a-1'],
      annualPurchaseVolumeBblMin: 4_000_000,
      annualPurchaseVolumeBblMax: 8_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 25_000, max: 55_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO', 'TT', 'JM', 'BB'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Decision-maker country is US (Chevron HQ San Ramon CA).',
      confidenceScore: 0.85,
    },
  },
  {
    slug: 'fuel-buyer:shell-caribbean',
    name: 'Shell Caribbean',
    country: 'NL',
    notes: 'Multiple country operations with cargo-import scale.',
    profile: {
      segments: ['industrial-distributor', 'retail-distributor-network'],
      fuelTypesPurchased: ['gasoline-87', 'gasoline-90', 'diesel-ulsd', 'jet-a-1', 'hfo-380cst'],
      annualPurchaseVolumeBblMin: 4_000_000,
      annualPurchaseVolumeBblMax: 9_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 25_000, max: 60_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS', 'JM', 'TT'],
      decisionMakerCountry: 'NL',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.82,
    },
  },
  {
    slug: 'fuel-buyer:total-energies-caribbean',
    name: 'TotalEnergies Caribbean',
    country: 'FR',
    aliases: ['Total Caribbean'],
    notes: 'Mostly French Caribbean (MQ, GP, GF) plus selected island operations.',
    profile: {
      segments: ['industrial-distributor', 'retail-distributor-network'],
      fuelTypesPurchased: ['gasoline-87', 'diesel-ulsd', 'jet-a-1'],
      annualPurchaseVolumeBblMin: 3_000_000,
      annualPurchaseVolumeBblMax: 6_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 25_000, max: 55_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['MQ', 'GP', 'GF', 'HT'],
      decisionMakerCountry: 'FR',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.85,
    },
  },
  {
    slug: 'fuel-buyer:national-petroleum-jamaica',
    name: 'National Petroleum (Jamaica)',
    country: 'JM',
    aliases: ['NP'],
    notes:
      'Jamaican independent fuel distributor with retail + commercial network. Long-running domestic operator.',
    profile: {
      segments: ['industrial-distributor', 'retail-distributor-network'],
      fuelTypesPurchased: ['gasoline-87', 'diesel-ulsd'],
      annualPurchaseVolumeBblMin: 1_500_000,
      annualPurchaseVolumeBblMax: 3_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 15_000, max: 35_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: ['Petrojam'],
      caribbeanCountriesOperated: ['JM'],
      decisionMakerCountry: 'JM',
      paymentInstrumentCapability: ['lc-sight', 'cad'],
      knownBanks: ['NCB Jamaica'],
      ownershipType: 'private-domestic',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.78,
    },
  },
  {
    slug: 'fuel-buyer:gb-energy-guyana',
    name: 'GB Energy (Guyana)',
    country: 'GY',
    notes: 'Guyanese fuel distributor; rapidly expanding with the offshore oil ramp-up.',
    profile: {
      segments: ['industrial-distributor', 'retail-distributor-network'],
      fuelTypesPurchased: ['gasoline-87', 'diesel-ulsd'],
      annualPurchaseVolumeBblMin: 500_000,
      annualPurchaseVolumeBblMax: 1_200_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 10_000, max: 25_000 },
      procurementModel: 'spot-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['GY'],
      decisionMakerCountry: 'GY',
      paymentInstrumentCapability: ['lc-sight', 'cad'],
      knownBanks: ['Republic Bank Guyana'],
      ownershipType: 'private-domestic',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.72,
    },
  },
  {
    slug: 'fuel-buyer:petroleos-dominicanos',
    name: 'Refinería Dominicana de Petróleo (REFIDOMSA)',
    country: 'DO',
    aliases: ['REFIDOMSA', 'Refidomsa PDV'],
    notes:
      'DR\'s state oil company; refines + distributes finished product. Sometimes imports finished product to supplement refining shortfall — captured here as a buyer-side touch in addition to its supplier-side rolodex entry.',
    profile: {
      segments: ['industrial-distributor'],
      fuelTypesPurchased: ['gasoline-87', 'gasoline-90', 'diesel-ulsd', 'hfo-380cst', 'jet-a-1'],
      annualPurchaseVolumeBblMin: 1_500_000,
      annualPurchaseVolumeBblMax: 4_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 25_000, max: 55_000 },
      procurementModel: 'tender-only',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO'],
      decisionMakerCountry: 'DO',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred', 'sblc-backed'],
      knownBanks: ['Banco de Reservas DR'],
      ownershipType: 'state-owned',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'PDVSA stake (49%) historical; current ownership structure subject to verification.',
      confidenceScore: 0.85,
    },
  },
];

export type IndustrialDistributorSeedRunSummary = SegmentRunSummary<'industrial-distributor-seed'>;

export async function runFuelBuyerIndustrialDistributorSeed(): Promise<IndustrialDistributorSeedRunSummary> {
  return ingestSegmentSeed('industrial-distributor-seed', SEED, 'industrial-distributor');
}
