/**
 * Tier-1 Caribbean mining-sector fuel buyers per
 * docs/caribbean-fuel-buyer-brief.md §4.2.
 *
 * Critical context from Petrojam disclosures: Jamaica's bauxite
 * companies alone import ~9M bbl/yr — 35% of national petroleum
 * consumption — direct cargo-scale buying that bypasses Petrojam
 * entirely. Multiply across Caribbean mining operations and this
 * is the second-largest cargo-volume buyer segment after utilities.
 *
 * Each entry carries a "status note" in `notes` when the operator's
 * recent operating history is intermittent — JISCO Alpart's
 * modernization shutdown, Falcondo's restart pattern, etc. —
 * because fuel-procurement profiles for intermittent operators
 * fluctuate dramatically year-to-year.
 */
import { ingestSegmentSeed, type FuelBuyerSeedEntry, type SegmentRunSummary } from './_shared';

const SEED: FuelBuyerSeedEntry[] = [
  {
    slug: 'fuel-buyer:jisco-alpart',
    name: 'JISCO Alpart',
    country: 'JM',
    aliases: ['Alpart Jamaica'],
    notes:
      'Alumina refinery in Nain, St. Elizabeth. Status note: operations suspended since 2019 for $1.1B modernization; phased reopening targeted Q4 2025. Verify operational status before treating as active buyer.',
    profile: {
      segments: ['mining-bauxite-alumina'],
      fuelTypesPurchased: ['hfo-380cst', 'diesel-ulsd'],
      annualPurchaseVolumeBblMin: 1_500_000,
      annualPurchaseVolumeBblMax: 3_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-capacity',
      typicalCargoSizeMt: { min: 25_000, max: 50_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM'],
      decisionMakerCountry: 'CN',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: 'General Manager',
      primaryContactName: null,
      notes: 'Owned 100% by Jiuquan Iron & Steel Group (JISCO) since 2016.',
      confidenceScore: 0.82,
    },
  },
  {
    slug: 'fuel-buyer:noranda-bauxite',
    name: 'Noranda Bauxite',
    country: 'JM',
    notes: 'Bauxite mining operation in St. Ann. Direct fuel importer.',
    profile: {
      segments: ['mining-bauxite-alumina'],
      fuelTypesPurchased: ['diesel-ulsd', 'hfo-380cst'],
      annualPurchaseVolumeBblMin: 800_000,
      annualPurchaseVolumeBblMax: 1_500_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 15_000, max: 30_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM'],
      decisionMakerCountry: 'JM',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred'],
      knownBanks: [],
      ownershipType: 'private-domestic',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.75,
    },
  },
  {
    slug: 'fuel-buyer:jamalco',
    name: 'Jamalco',
    country: 'JM',
    aliases: ['Clarendon Alumina', 'Jamaica Alumina Company'],
    notes: 'Alumina refinery JV in Hayes, Clarendon. Government of Jamaica + Noble Group.',
    profile: {
      segments: ['mining-bauxite-alumina'],
      fuelTypesPurchased: ['hfo-380cst', 'diesel-ulsd'],
      annualPurchaseVolumeBblMin: 2_000_000,
      annualPurchaseVolumeBblMax: 3_500_000,
      annualPurchaseVolumeConfidence: 'estimated-from-capacity',
      typicalCargoSizeMt: { min: 25_000, max: 50_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM'],
      decisionMakerCountry: 'JM',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'state-adjacent',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'JV: 45% Government of Jamaica via Clarendon Alumina, 55% Noble Group / General Alumina.',
      confidenceScore: 0.82,
    },
  },
  {
    slug: 'fuel-buyer:windalco',
    name: 'Windalco',
    country: 'JM',
    aliases: ['West Indies Alumina Company'],
    notes: 'Alumina operations in Ewarton + Kirkvine. Owned by UC Rusal.',
    profile: {
      segments: ['mining-bauxite-alumina'],
      fuelTypesPurchased: ['hfo-380cst', 'diesel-ulsd'],
      annualPurchaseVolumeBblMin: 1_500_000,
      annualPurchaseVolumeBblMax: 2_800_000,
      annualPurchaseVolumeConfidence: 'estimated-from-capacity',
      typicalCargoSizeMt: { min: 20_000, max: 45_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM'],
      decisionMakerCountry: 'RU',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Owned by UC Rusal. Sanctions overlay considerations for any deal sourcing.',
      confidenceScore: 0.85,
    },
  },
  {
    slug: 'fuel-buyer:barrick-pueblo-viejo',
    name: 'Barrick Pueblo Viejo',
    country: 'DO',
    aliases: ['Pueblo Viejo Mine', 'Barrick / Newmont Pueblo Viejo'],
    notes:
      'One of the largest gold mines in the Americas. JV between Barrick (60%) and Newmont (40%). Significant fuel consumption for haulage + processing.',
    profile: {
      segments: ['mining-gold'],
      fuelTypesPurchased: ['diesel-ulsd', 'hfo-380cst'],
      annualPurchaseVolumeBblMin: 1_800_000,
      annualPurchaseVolumeBblMax: 3_200_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 25_000, max: 45_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO'],
      decisionMakerCountry: 'CA',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: 'Procurement Director',
      primaryContactName: null,
      notes: 'Decision-maker country is Canada (Barrick HQ).',
      confidenceScore: 0.92,
    },
  },
  {
    slug: 'fuel-buyer:falcondo',
    name: 'Falconbridge Dominicana (Falcondo)',
    country: 'DO',
    aliases: ['Falcondo'],
    notes:
      'Ferronickel operation in Bonao. Status note: operations have been intermittent since Americano Nickel acquired from Glencore in 2015. Verify production status before treating as active fuel buyer.',
    profile: {
      segments: ['mining-nickel'],
      fuelTypesPurchased: ['hfo-380cst', 'diesel-ulsd'],
      annualPurchaseVolumeBblMin: 600_000,
      annualPurchaseVolumeBblMax: 1_500_000,
      annualPurchaseVolumeConfidence: 'estimated-from-capacity',
      typicalCargoSizeMt: { min: 15_000, max: 30_000 },
      procurementModel: 'hybrid',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['DO'],
      decisionMakerCountry: 'BS',
      paymentInstrumentCapability: ['lc-sight', 'lc-deferred'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Owned by Americano Nickel Ltd (Bahamas-based subsidiary of Global Special Opportunities Ltd).',
      confidenceScore: 0.7,
    },
  },
  {
    slug: 'fuel-buyer:iamgold-rosebel',
    name: 'IAmGold Rosebel',
    country: 'SR',
    notes:
      'Surinamese gold mine, fuel-intensive open-pit + heap leach operation.',
    profile: {
      segments: ['mining-gold'],
      fuelTypesPurchased: ['diesel-ulsd'],
      annualPurchaseVolumeBblMin: 600_000,
      annualPurchaseVolumeBblMax: 1_200_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 12_000, max: 25_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['SR'],
      decisionMakerCountry: 'CA',
      paymentInstrumentCapability: ['lc-sight', 'open-account'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Owned by Zijin Mining (CN) post 2023 IAmGold sale.',
      confidenceScore: 0.85,
    },
  },
  {
    slug: 'fuel-buyer:newmont-merian',
    name: 'Newmont Merian',
    country: 'SR',
    notes: 'Newmont gold mine in eastern Suriname. Major diesel consumer.',
    profile: {
      segments: ['mining-gold'],
      fuelTypesPurchased: ['diesel-ulsd'],
      annualPurchaseVolumeBblMin: 800_000,
      annualPurchaseVolumeBblMax: 1_500_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 15_000, max: 30_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['SR'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Decision-maker country is US (Newmont HQ Denver).',
      confidenceScore: 0.88,
    },
  },
];

export type MiningSeedRunSummary = SegmentRunSummary<'mining-seed'>;

export async function runFuelBuyerMiningSeed(): Promise<MiningSeedRunSummary> {
  return ingestSegmentSeed('mining-seed', SEED, 'mining');
}
