/**
 * Tier-1 Caribbean aviation fuel buyers per
 * docs/caribbean-fuel-buyer-brief.md §4.4. Caribbean tourism drives
 * substantial Jet-A consumption; airport handlers + airlines that
 * purchase directly through master contracts both surface here.
 */
import { ingestSegmentSeed, type FuelBuyerSeedEntry, type SegmentRunSummary } from './_shared';

const SEED: FuelBuyerSeedEntry[] = [
  {
    slug: 'fuel-buyer:wfs-aviation',
    name: 'World Fuel Services — Aviation',
    country: 'US',
    aliases: ['WFS Aviation', 'World Kinect Aviation'],
    notes:
      'Global aviation fuel supplier with multiple Caribbean airport contracts. Distinct rolodex entry from the WFS marine bunkering arm.',
    profile: {
      segments: ['aviation-fuel-handler'],
      fuelTypesPurchased: ['jet-a-1', 'avgas-100ll'],
      annualPurchaseVolumeBblMin: 4_000_000,
      annualPurchaseVolumeBblMax: 8_000_000,
      annualPurchaseVolumeConfidence: 'public-disclosure',
      typicalCargoSizeMt: { min: 20_000, max: 50_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM', 'BS', 'PR', 'BB', 'TT', 'DO'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Decision-maker country is US (Miami HQ).',
      confidenceScore: 0.9,
    },
  },
  {
    slug: 'fuel-buyer:air-bp',
    name: 'Air BP',
    country: 'GB',
    notes:
      'BP\'s aviation fuel arm. Active across Caribbean airport contracts including Sangster (MBJ), Punta Cana (PUJ), Nassau (NAS).',
    profile: {
      segments: ['aviation-fuel-handler'],
      fuelTypesPurchased: ['jet-a-1', 'avgas-100ll'],
      annualPurchaseVolumeBblMin: 2_000_000,
      annualPurchaseVolumeBblMax: 5_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 20_000, max: 45_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['JM', 'BS', 'DO'],
      decisionMakerCountry: 'GB',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.88,
    },
  },
  {
    slug: 'fuel-buyer:shell-aviation-caribbean',
    name: 'Shell Aviation Caribbean',
    country: 'NL',
    aliases: ['Shell Aviation'],
    notes: 'Shell\'s aviation arm covering Caribbean airport contracts.',
    profile: {
      segments: ['aviation-fuel-handler'],
      fuelTypesPurchased: ['jet-a-1', 'avgas-100ll'],
      annualPurchaseVolumeBblMin: 1_500_000,
      annualPurchaseVolumeBblMax: 4_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 18_000, max: 40_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS', 'TT', 'JM'],
      decisionMakerCountry: 'NL',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.85,
    },
  },
  {
    slug: 'fuel-buyer:exxonmobil-aviation-caribbean',
    name: 'ExxonMobil Aviation Caribbean',
    country: 'US',
    aliases: ['ExxonMobil Aviation'],
    notes: 'ExxonMobil aviation contracts at multiple Caribbean airports including SJU + PUJ.',
    profile: {
      segments: ['aviation-fuel-handler'],
      fuelTypesPurchased: ['jet-a-1', 'avgas-100ll'],
      annualPurchaseVolumeBblMin: 2_000_000,
      annualPurchaseVolumeBblMax: 5_000_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 20_000, max: 45_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['PR', 'DO', 'BS'],
      decisionMakerCountry: 'US',
      paymentInstrumentCapability: ['lc-sight', 'open-account', 'sblc-backed'],
      knownBanks: [],
      ownershipType: 'multinational-subsidiary',
      tier: 1,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.85,
    },
  },
  {
    slug: 'fuel-buyer:caribbean-airlines',
    name: 'Caribbean Airlines',
    country: 'TT',
    notes:
      'Trinidad-based regional carrier. Direct fuel procurement across regional network.',
    profile: {
      segments: ['aviation-airline-direct'],
      fuelTypesPurchased: ['jet-a-1'],
      annualPurchaseVolumeBblMin: 800_000,
      annualPurchaseVolumeBblMax: 1_500_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 12_000, max: 25_000 },
      procurementModel: 'term-contract-dominant',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['TT', 'JM', 'BB', 'GY'],
      decisionMakerCountry: 'TT',
      paymentInstrumentCapability: ['lc-sight'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: 'Government of Trinidad and Tobago majority owned.',
      confidenceScore: 0.78,
    },
  },
  {
    slug: 'fuel-buyer:bahamasair',
    name: 'Bahamasair',
    country: 'BS',
    notes: 'Bahamas national carrier. Direct fuel procurement primarily out of Nassau.',
    profile: {
      segments: ['aviation-airline-direct'],
      fuelTypesPurchased: ['jet-a-1'],
      annualPurchaseVolumeBblMin: 200_000,
      annualPurchaseVolumeBblMax: 500_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 6_000, max: 14_000 },
      procurementModel: 'tender-only',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['BS'],
      decisionMakerCountry: 'BS',
      paymentInstrumentCapability: ['lc-sight'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 2,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.72,
    },
  },
  {
    slug: 'fuel-buyer:cayman-airways',
    name: 'Cayman Airways',
    country: 'KY',
    notes: 'Cayman Islands national carrier.',
    profile: {
      segments: ['aviation-airline-direct'],
      fuelTypesPurchased: ['jet-a-1'],
      annualPurchaseVolumeBblMin: 100_000,
      annualPurchaseVolumeBblMax: 300_000,
      annualPurchaseVolumeConfidence: 'estimated-from-industry-norms',
      typicalCargoSizeMt: { min: 4_000, max: 10_000 },
      procurementModel: 'tender-only',
      procurementAuthority: 'centralized',
      knownSuppliers: [],
      caribbeanCountriesOperated: ['KY'],
      decisionMakerCountry: 'KY',
      paymentInstrumentCapability: ['lc-sight'],
      knownBanks: [],
      ownershipType: 'state-owned',
      tier: 3,
      primaryContactRole: null,
      primaryContactName: null,
      notes: '',
      confidenceScore: 0.72,
    },
  },
];

export type AviationSeedRunSummary = SegmentRunSummary<'aviation-seed'>;

export async function runFuelBuyerAviationSeed(): Promise<AviationSeedRunSummary> {
  return ingestSegmentSeed('aviation-seed', SEED, 'aviation');
}
