import type { NewJurisdiction, NewAgency, NewTaxonomyCategory } from './schema';

export const seedJurisdictions: Array<
  Omit<NewJurisdiction, 'createdAt' | 'updatedAt'> & { agencies: string[][] }
> = [
  {
    name: 'Jamaica',
    slug: 'jamaica',
    countryCode: 'JM',
    region: 'caribbean',
    portalName: 'Government of Jamaica Electronic Procurement (GOJEP)',
    portalUrl: 'https://www.gojep.gov.jm',
    scraperModule: 'jamaica-gojep',
    currency: 'JMD',
    language: 'en',
    timezone: 'America/Jamaica',
    active: true,
    agencies: [
      ['Ministry of Finance and the Public Service', 'MoFPS', 'ministry'],
      ['Ministry of Health and Wellness', 'MoHW', 'ministry'],
      ['Ministry of Education, Youth and Information', 'MoEYI', 'ministry'],
      ['National Works Agency', 'NWA', 'agency'],
      ['Jamaica Public Service Company', 'JPS', 'parastatal'],
      ['Urban Development Corporation', 'UDC', 'agency'],
    ],
  },
  {
    name: 'Guyana',
    slug: 'guyana',
    countryCode: 'GY',
    region: 'caribbean',
    portalName: 'National Procurement and Tender Administration Board',
    portalUrl: 'https://nptab.gov.gy',
    scraperModule: 'guyana-nptab',
    currency: 'GYD',
    language: 'en',
    timezone: 'America/Guyana',
    active: true,
    agencies: [
      ['Ministry of Finance', 'MoF', 'ministry'],
      ['Ministry of Public Works', 'MoPW', 'ministry'],
      ['Ministry of Health', 'MoH', 'ministry'],
      ['Guyana Power and Light', 'GPL', 'parastatal'],
      ['Guyana Water Incorporated', 'GWI', 'parastatal'],
      ['Ministry of Education', 'MoE', 'ministry'],
    ],
  },
  {
    name: 'Trinidad and Tobago',
    slug: 'trinidad-and-tobago',
    countryCode: 'TT',
    region: 'caribbean',
    portalName: 'Trinidad and Tobago Electronic Government Procurement',
    portalUrl: 'https://egp.gov.tt',
    scraperModule: 'trinidad-egp',
    currency: 'TTD',
    language: 'en',
    timezone: 'America/Port_of_Spain',
    active: true,
    agencies: [
      ['Ministry of Finance', 'MoF', 'ministry'],
      ['Ministry of Health', 'MoH', 'ministry'],
      ['Ministry of Works and Transport', 'MoWT', 'ministry'],
      ['Water and Sewerage Authority', 'WASA', 'parastatal'],
      ['Petroleum Company of Trinidad and Tobago', 'Petrotrin', 'parastatal'],
      ['Trinidad and Tobago Electricity Commission', 'T&TEC', 'parastatal'],
    ],
  },
  {
    name: 'Barbados',
    slug: 'barbados',
    countryCode: 'BB',
    region: 'caribbean',
    portalName: 'Government of Barbados Procurement',
    portalUrl: 'https://gisbarbados.gov.bb',
    scraperModule: 'barbados-gis',
    currency: 'BBD',
    language: 'en',
    timezone: 'America/Barbados',
    active: false,
    agencies: [
      ['Ministry of Finance, Economic Affairs and Investment', 'MoFEAI', 'ministry'],
      ['Ministry of Health and Wellness', 'MoHW', 'ministry'],
      ['Ministry of Transport, Works and Water Resources', 'MoTWWR', 'ministry'],
      ['Barbados Light and Power Company', 'BL&P', 'parastatal'],
      ['Barbados Water Authority', 'BWA', 'parastatal'],
    ],
  },
  {
    name: 'Bahamas',
    slug: 'bahamas',
    countryCode: 'BS',
    region: 'caribbean',
    portalName: 'Bahamas Government Procurement Portal',
    portalUrl: 'https://www.bahamas.gov.bs',
    scraperModule: 'bahamas-gpp',
    currency: 'BSD',
    language: 'en',
    timezone: 'America/Nassau',
    active: false,
    agencies: [
      ['Ministry of Finance', 'MoF', 'ministry'],
      ['Ministry of Health and Wellness', 'MoHW', 'ministry'],
      ['Ministry of Works and Utilities', 'MoWU', 'ministry'],
      ['Bahamas Power and Light', 'BPL', 'parastatal'],
      ['Water and Sewerage Corporation', 'WSC', 'parastatal'],
    ],
  },
  {
    name: 'Dominican Republic',
    slug: 'dominican-republic',
    countryCode: 'DO',
    region: 'caribbean',
    portalName: 'Dirección General de Contrataciones Públicas',
    portalUrl: 'https://comunidad.comprasdominicana.gob.do',
    scraperModule: 'dr-dgcp',
    currency: 'DOP',
    language: 'es',
    timezone: 'America/Santo_Domingo',
    active: true,
    agencies: [
      ['Ministerio de Hacienda', 'MH', 'ministry'],
      ['Ministerio de Salud Pública', 'MSP', 'ministry'],
      ['Ministerio de Obras Públicas y Comunicaciones', 'MOPC', 'ministry'],
      ['Corporación Dominicana de Empresas Eléctricas Estatales', 'CDEEE', 'parastatal'],
      ['Instituto Nacional de Aguas Potables y Alcantarillados', 'INAPA', 'parastatal'],
    ],
  },
  {
    name: 'Saint Lucia',
    slug: 'saint-lucia',
    countryCode: 'LC',
    region: 'caribbean',
    portalName: 'Government of Saint Lucia Procurement',
    portalUrl: 'https://www.govt.lc',
    scraperModule: 'saintlucia-gov',
    currency: 'XCD',
    language: 'en',
    timezone: 'America/St_Lucia',
    active: false,
    agencies: [
      ['Ministry of Finance, Economic Development and Youth Economy', 'MoF', 'ministry'],
      ['Ministry of Health, Wellness and Elderly Affairs', 'MoH', 'ministry'],
      ['Ministry of Infrastructure', 'MoI', 'ministry'],
      ['LUCELEC', 'LUCELEC', 'parastatal'],
      ['Water and Sewerage Company', 'WASCO', 'parastatal'],
    ],
  },
  {
    name: 'Caribbean Development Bank',
    slug: 'cdb',
    countryCode: 'BB',
    region: 'caribbean',
    portalName: 'CDB Procurement Notices',
    portalUrl: 'https://www.caribank.org',
    scraperModule: 'cdb-procurement',
    currency: 'USD',
    language: 'en',
    timezone: 'America/Barbados',
    active: false,
    agencies: [
      ['Caribbean Development Bank', 'CDB', 'development_bank'],
      ['CDB Basic Needs Trust Fund', 'BNTF', 'development_bank'],
      ['CDB Project Management Unit', 'PMU', 'development_bank'],
    ],
  },
  {
    name: 'Inter-American Development Bank',
    slug: 'idb',
    countryCode: 'US',
    region: 'latam',
    portalName: 'IDB Procurement',
    portalUrl: 'https://www.iadb.org',
    scraperModule: 'idb-procurement',
    currency: 'USD',
    language: 'en',
    timezone: 'America/New_York',
    active: false,
    agencies: [
      ['Inter-American Development Bank', 'IDB', 'development_bank'],
      ['IDB Invest', 'IDB Invest', 'development_bank'],
      ['IDB Lab', 'IDB Lab', 'development_bank'],
    ],
  },
  {
    name: 'World Bank (LAC Region)',
    slug: 'worldbank-lac',
    countryCode: 'US',
    region: 'latam',
    portalName: 'World Bank Procurement Notices',
    portalUrl: 'https://projects.worldbank.org',
    scraperModule: 'worldbank-lac',
    currency: 'USD',
    language: 'en',
    timezone: 'America/New_York',
    active: false,
    agencies: [
      ['World Bank LAC Procurement', 'WB LAC', 'development_bank'],
      ['IFC', 'IFC', 'development_bank'],
    ],
  },
  {
    name: 'United Nations',
    slug: 'un',
    // 'UN' isn't a real ISO country code but the regional-indicator
    // emoji renders as the UN flag on most platforms. flagFor() is
    // resilient — at worst it falls back to 🏳️.
    countryCode: 'UN',
    region: 'global',
    portalName: 'UN Global Marketplace (UNGM)',
    portalUrl: 'https://www.ungm.org',
    scraperModule: 'ungm',
    currency: 'USD',
    language: 'en',
    timezone: 'UTC',
    active: true,
    agencies: [
      ['World Food Programme', 'WFP', 'multilateral'],
      ['UN Development Programme', 'UNDP', 'multilateral'],
      ['UN High Commissioner for Refugees', 'UNHCR', 'multilateral'],
      ['UNICEF', 'UNICEF', 'multilateral'],
      ['World Health Organization', 'WHO', 'multilateral'],
      ['Food and Agriculture Organization', 'FAO', 'multilateral'],
      ['UN Population Fund', 'UNFPA', 'multilateral'],
      ['International Atomic Energy Agency', 'IAEA', 'multilateral'],
      ['UN Office for Project Services', 'UNOPS', 'multilateral'],
    ],
  },
  {
    name: 'United States Federal',
    slug: 'us-federal',
    countryCode: 'US',
    region: 'global',
    portalName: 'SAM.gov',
    portalUrl: 'https://sam.gov',
    scraperModule: 'sam-gov',
    currency: 'USD',
    language: 'en',
    timezone: 'America/New_York',
    active: true,
    agencies: [
      ['Defense Logistics Agency', 'DLA', 'agency'],
      ['U.S. Agency for International Development', 'USAID', 'agency'],
      ['U.S. Department of Agriculture', 'USDA', 'ministry'],
      ['General Services Administration', 'GSA', 'agency'],
      ['U.S. Department of State', 'DOS', 'ministry'],
      ['U.S. Department of Defense', 'DOD', 'ministry'],
      ['U.S. Department of Energy', 'DOE', 'ministry'],
      ['U.S. Department of Veterans Affairs', 'VA', 'ministry'],
      ['U.S. Department of Homeland Security', 'DHS', 'ministry'],
    ],
  },
  {
    name: 'Colombia',
    slug: 'colombia',
    countryCode: 'CO',
    region: 'latam',
    portalName: 'SECOP — Sistema Electrónico de Contratación Pública',
    portalUrl: 'https://www.colombiacompra.gov.co',
    scraperModule: 'colombia-secop',
    currency: 'COP',
    language: 'es',
    timezone: 'America/Bogota',
    active: true,
    agencies: [
      ['Agencia Nacional de Contratación Pública - Colombia Compra Eficiente', 'CCE', 'agency'],
      ['Ministerio de Hacienda y Crédito Público', 'MHCP', 'ministry'],
      ['Ministerio de Salud y Protección Social', 'MSPS', 'ministry'],
      ['Instituto Nacional de Vías', 'INVIAS', 'agency'],
    ],
  },
  {
    name: 'Peru',
    slug: 'peru',
    countryCode: 'PE',
    region: 'latam',
    portalName: 'SEACE — Sistema Electrónico de Contrataciones del Estado',
    portalUrl: 'https://www.gob.pe/seace',
    scraperModule: 'peru-seace',
    currency: 'PEN',
    language: 'es',
    timezone: 'America/Lima',
    active: false,
    agencies: [
      ['Organismo Supervisor de las Contrataciones del Estado', 'OSCE', 'agency'],
      ['Ministerio de Economía y Finanzas', 'MEF', 'ministry'],
      ['Ministerio de Salud', 'MINSA', 'ministry'],
    ],
  },
  {
    name: 'Chile',
    slug: 'chile',
    countryCode: 'CL',
    region: 'latam',
    portalName: 'Mercado Público — ChileCompra',
    portalUrl: 'https://www.mercadopublico.cl',
    scraperModule: 'chile-mp',
    currency: 'CLP',
    language: 'es',
    timezone: 'America/Santiago',
    active: true,
    agencies: [
      ['Dirección ChileCompra', 'ChileCompra', 'agency'],
      ['Ministerio de Salud', 'MINSAL', 'ministry'],
      ['Ministerio de Obras Públicas', 'MOP', 'ministry'],
      ['Empresa Nacional del Petróleo', 'ENAP', 'parastatal'],
      ['Servicio de Salud Metropolitano', 'SSM', 'agency'],
    ],
  },
  {
    name: 'Kenya',
    slug: 'kenya',
    countryCode: 'KE',
    region: 'africa',
    portalName: 'Public Procurement Information Portal (PPIP)',
    portalUrl: 'https://tenders.go.ke',
    scraperModule: 'kenya-ppip',
    currency: 'KES',
    language: 'en',
    timezone: 'Africa/Nairobi',
    active: false,
    agencies: [
      ['National Treasury', 'NT', 'ministry'],
      ['Ministry of Health', 'MoH', 'ministry'],
      ['Kenya National Highways Authority', 'KeNHA', 'agency'],
      ['Kenya Power and Lighting Company', 'KPLC', 'parastatal'],
    ],
  },
  {
    name: 'Ghana',
    slug: 'ghana',
    countryCode: 'GH',
    region: 'africa',
    portalName: 'Public Procurement Authority Tender Portal',
    portalUrl: 'https://tenders.gov.gh',
    scraperModule: 'ghana-ppa',
    currency: 'GHS',
    language: 'en',
    timezone: 'Africa/Accra',
    active: false,
    agencies: [
      ['Ministry of Finance', 'MoF', 'ministry'],
      ['Ministry of Health', 'MoH', 'ministry'],
      ['Ghana Highway Authority', 'GHA', 'agency'],
      ['Electricity Company of Ghana', 'ECG', 'parastatal'],
    ],
  },
  {
    name: 'Rwanda',
    slug: 'rwanda',
    countryCode: 'RW',
    region: 'africa',
    portalName: 'Rwanda Public Procurement Authority',
    portalUrl: 'https://www.umucyo.gov.rw',
    scraperModule: 'rwanda-umucyo',
    currency: 'RWF',
    language: 'en',
    timezone: 'Africa/Kigali',
    active: false,
    agencies: [
      ['Ministry of Finance and Economic Planning', 'MINECOFIN', 'ministry'],
      ['Ministry of Health', 'MoH', 'ministry'],
      ['Rwanda Transport Development Agency', 'RTDA', 'agency'],
    ],
  },
];

export const seedTaxonomyCategories: Array<Omit<NewTaxonomyCategory, 'createdAt'>> = [
  { slug: 'construction', name: 'Construction', sortOrder: 10 },
  { slug: 'infrastructure', name: 'Infrastructure', sortOrder: 20 },
  { slug: 'roads-highways', name: 'Roads and Highways', parentSlug: 'infrastructure', sortOrder: 21 },
  { slug: 'buildings', name: 'Buildings', parentSlug: 'construction', sortOrder: 11 },
  { slug: 'water-sanitation', name: 'Water and Sanitation', sortOrder: 30 },
  { slug: 'energy-utilities', name: 'Energy and Utilities', sortOrder: 40 },
  { slug: 'renewable-energy', name: 'Renewable Energy', parentSlug: 'energy-utilities', sortOrder: 41 },
  { slug: 'it-services', name: 'IT Services', sortOrder: 50 },
  { slug: 'software-development', name: 'Software Development', parentSlug: 'it-services', sortOrder: 51 },
  { slug: 'cybersecurity', name: 'Cybersecurity', parentSlug: 'it-services', sortOrder: 52 },
  { slug: 'cloud-infrastructure', name: 'Cloud Infrastructure', parentSlug: 'it-services', sortOrder: 53 },
  { slug: 'telecommunications', name: 'Telecommunications', sortOrder: 60 },
  { slug: 'consulting', name: 'Consulting Services', sortOrder: 70 },
  { slug: 'management-consulting', name: 'Management Consulting', parentSlug: 'consulting', sortOrder: 71 },
  { slug: 'financial-advisory', name: 'Financial Advisory', parentSlug: 'consulting', sortOrder: 72 },
  { slug: 'engineering', name: 'Engineering Services', sortOrder: 80 },
  { slug: 'civil-engineering', name: 'Civil Engineering', parentSlug: 'engineering', sortOrder: 81 },
  { slug: 'mechanical-engineering', name: 'Mechanical Engineering', parentSlug: 'engineering', sortOrder: 82 },
  { slug: 'healthcare', name: 'Healthcare', sortOrder: 90 },
  { slug: 'medical-supplies', name: 'Medical Supplies and Equipment', parentSlug: 'healthcare', sortOrder: 91 },
  { slug: 'pharmaceuticals', name: 'Pharmaceuticals', parentSlug: 'healthcare', sortOrder: 92 },
  { slug: 'education', name: 'Education', sortOrder: 100 },
  { slug: 'school-supplies', name: 'School Supplies and Equipment', parentSlug: 'education', sortOrder: 101 },
  { slug: 'training', name: 'Training and Capacity Building', parentSlug: 'education', sortOrder: 102 },
  { slug: 'agriculture', name: 'Agriculture and Agribusiness', sortOrder: 110 },
  { slug: 'transport-logistics', name: 'Transport and Logistics', sortOrder: 120 },
  { slug: 'security-services', name: 'Security Services', sortOrder: 130 },
  { slug: 'legal-services', name: 'Legal Services', sortOrder: 140 },
  { slug: 'accounting-audit', name: 'Accounting and Audit', sortOrder: 150 },
  { slug: 'marketing-comms', name: 'Marketing and Communications', sortOrder: 160 },
  { slug: 'environment', name: 'Environmental Services', sortOrder: 170 },
  { slug: 'waste-management', name: 'Waste Management', parentSlug: 'environment', sortOrder: 171 },
  { slug: 'facilities-maintenance', name: 'Facilities Maintenance', sortOrder: 180 },
  { slug: 'office-supplies', name: 'Office Supplies and Equipment', sortOrder: 190 },
  { slug: 'vehicles-fleet', name: 'Vehicles and Fleet', sortOrder: 200 },
  { slug: 'social-services', name: 'Social Services', sortOrder: 210 },
  { slug: 'research', name: 'Research and Development', sortOrder: 220 },
];
