'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';

/**
 * RVM audio asset panel on the probe page. PR 1 ships the upload-
 * only flow: operator drag-drops an .mp3 / .wav generated externally
 * (ElevenLabs UI, Voicebox export, hand recording, Slybroadcast
 * asset library). PR 2 will add browser-side Voicebox integration
 * that calls localhost:17493/generate from the browser and forwards
 * bytes to this same API endpoint.
 *
 * Visual model:
 *   - List of assets, grouped by language, with active/retired
 *     badges + audio preview
 *   - Upload form: file + language + sourceText + variant scope
 *     (probe-default OR specific variant) + generation source
 */

interface AudioAssetRow {
  id: string;
  probeId: string;
  variantId: string | null;
  language: string;
  sourceText: string;
  audioUrl: string;
  audioFormat: string;
  durationMs: number | null;
  voiceProfileId: string | null;
  generatedVia: string;
  generatedAt: Date;
  isActive: boolean;
}

interface VariantSummary {
  id: string;
  name: string;
}

export function RvmAudioPanel({
  probeId,
  probeOutreachLanguage,
  variants,
  assets,
}: {
  probeId: string;
  probeOutreachLanguage: string | null;
  variants: VariantSummary[];
  assets: AudioAssetRow[];
}) {
  const router = useRouter();
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const activeAssets = assets.filter((a) => a.isActive);
  const retiredAssets = assets.filter((a) => !a.isActive);

  const handleUpload = async (formData: FormData) => {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch('/api/rvm/audio-assets', {
        method: 'POST',
        body: formData,
      });
      if (!res.ok) {
        const body = (await res.json().catch(() => ({}))) as {
          error?: string;
        };
        setError(body.error ?? `upload failed (${res.status})`);
        return;
      }
      router.refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'unknown error');
    } finally {
      setBusy(false);
    }
  };

  const handleRetire = async (assetId: string) => {
    if (!confirm('Retire this audio asset? It can be reactivated later.')) {
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(`/api/rvm/audio-assets/${assetId}`, {
        method: 'DELETE',
      });
      if (!res.ok) {
        setError(`retire failed (${res.status})`);
        return;
      }
      router.refresh();
    } finally {
      setBusy(false);
    }
  };

  const handleReactivate = async (assetId: string) => {
    setBusy(true);
    setError(null);
    try {
      const res = await fetch(`/api/rvm/audio-assets/${assetId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'reactivate' }),
      });
      if (!res.ok) {
        setError(`reactivate failed (${res.status})`);
        return;
      }
      router.refresh();
    } finally {
      setBusy(false);
    }
  };

  return (
    <section className="mt-6 rounded-[var(--radius-lg)] border border-[color:var(--color-border)] p-5">
      <h2 className="mb-1 text-sm font-semibold uppercase tracking-wide text-[color:var(--color-muted-foreground)]">
        RVM audio assets ({activeAssets.length} active)
      </h2>
      <p className="mb-4 text-xs text-[color:var(--color-muted-foreground)]">
        Pre-recorded audio Twilio plays into recipients&apos; voicemail
        boxes via MachineDetection. Per (probe, variant, language) —
        variant-specific wins over probe-default. Upload an .mp3 or
        .wav generated by Voicebox, ElevenLabs, or your preferred TTS.
      </p>

      {error && (
        <p className="mb-3 rounded-[var(--radius-md)] bg-red-50 px-3 py-1.5 text-xs text-red-900">
          {error}
        </p>
      )}

      {/* Active asset list */}
      {activeAssets.length > 0 && (
        <div className="mb-5 space-y-2">
          {activeAssets.map((a) => (
            <AudioAssetRowView
              key={a.id}
              asset={a}
              variants={variants}
              onAction={() => void handleRetire(a.id)}
              actionLabel="Retire"
              busy={busy}
            />
          ))}
        </div>
      )}

      {/* Upload form */}
      <details className="mb-3 rounded-[var(--radius-md)] border border-dashed border-[color:var(--color-border)] p-3">
        <summary className="cursor-pointer text-xs font-medium">
          Upload new audio
        </summary>
        <form
          className="mt-3 grid gap-2 text-xs"
          onSubmit={(e) => {
            e.preventDefault();
            const fd = new FormData(e.currentTarget);
            fd.set('probeId', probeId);
            fd.set('generatedVia', 'manual_upload');
            void handleUpload(fd);
          }}
        >
          <label className="grid gap-1">
            <span>Audio file (.mp3 / .wav, max 5 MB)</span>
            <input
              type="file"
              name="file"
              accept="audio/mpeg,audio/mp3,audio/wav,audio/wave,audio/x-wav"
              required
              disabled={busy}
              className="text-xs"
            />
          </label>
          <label className="grid gap-1">
            <span>Language (ISO 639-1 lowercase)</span>
            <input
              type="text"
              name="language"
              defaultValue={probeOutreachLanguage ?? 'en'}
              maxLength={2}
              pattern="[a-z]{2}"
              required
              disabled={busy}
              className="w-20 rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-background)] px-1 py-0.5"
            />
          </label>
          <label className="grid gap-1">
            <span>Variant scope</span>
            <select
              name="variantId"
              disabled={busy}
              className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-background)] px-1 py-0.5"
            >
              <option value="">Probe default (all variants)</option>
              {variants.map((v) => (
                <option key={v.id} value={v.id}>
                  Variant: {v.name}
                </option>
              ))}
            </select>
          </label>
          <label className="grid gap-1">
            <span>
              Source text (transcript — what the audio says, for
              audit + retranslation)
            </span>
            <textarea
              name="sourceText"
              required
              maxLength={4000}
              rows={3}
              disabled={busy}
              placeholder="Hi, this is Cole at Procur — calling about your refinery's Q3 distillates supply…"
              className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-background)] px-1 py-1"
            />
          </label>
          <label className="grid gap-1">
            <span>Voice profile id (optional — Voicebox profile UUID)</span>
            <input
              type="text"
              name="voiceProfileId"
              maxLength={200}
              disabled={busy}
              className="rounded-[var(--radius-sm)] border border-[color:var(--color-border)] bg-[color:var(--color-background)] px-1 py-0.5 font-mono"
            />
          </label>
          <button
            type="submit"
            disabled={busy}
            className="self-start rounded-[var(--radius-md)] bg-[color:var(--color-foreground)] px-3 py-1 text-xs font-medium text-[color:var(--color-background)] disabled:opacity-50"
          >
            {busy ? 'Uploading…' : 'Upload audio'}
          </button>
        </form>
      </details>

      {/* Retired audit history */}
      {retiredAssets.length > 0 && (
        <details className="text-xs">
          <summary className="cursor-pointer text-[color:var(--color-muted-foreground)]">
            Retired ({retiredAssets.length})
          </summary>
          <div className="mt-2 space-y-2 opacity-70">
            {retiredAssets.map((a) => (
              <AudioAssetRowView
                key={a.id}
                asset={a}
                variants={variants}
                onAction={() => void handleReactivate(a.id)}
                actionLabel="Reactivate"
                busy={busy}
              />
            ))}
          </div>
        </details>
      )}
    </section>
  );
}

function AudioAssetRowView({
  asset,
  variants,
  onAction,
  actionLabel,
  busy,
}: {
  asset: AudioAssetRow;
  variants: VariantSummary[];
  onAction: () => void;
  actionLabel: string;
  busy: boolean;
}) {
  const variantName = asset.variantId
    ? variants.find((v) => v.id === asset.variantId)?.name ?? '(unknown variant)'
    : null;
  const durationSec = asset.durationMs
    ? Math.round(asset.durationMs / 100) / 10
    : null;
  return (
    <div className="grid gap-1 rounded-[var(--radius-md)] border border-[color:var(--color-border)] p-3">
      <div className="flex flex-wrap items-baseline gap-2 text-xs">
        <span className="rounded-full bg-[color:var(--color-muted)]/60 px-2 py-0.5 font-mono uppercase">
          {asset.language}
        </span>
        <span className="text-[color:var(--color-muted-foreground)]">
          {variantName ? `Variant: ${variantName}` : 'Probe default'}
        </span>
        <span className="text-[color:var(--color-muted-foreground)]">
          via {asset.generatedVia}
        </span>
        {durationSec != null && (
          <span className="text-[color:var(--color-muted-foreground)]">
            {durationSec}s
          </span>
        )}
        <button
          type="button"
          onClick={onAction}
          disabled={busy}
          className="ml-auto rounded-[var(--radius-sm)] border border-[color:var(--color-border)] px-2 py-0.5 text-[10px] hover:bg-[color:var(--color-muted)]/40 disabled:opacity-50"
        >
          {actionLabel}
        </button>
      </div>
      <audio controls src={asset.audioUrl} className="w-full" />
      <p className="text-[10px] text-[color:var(--color-muted-foreground)]">
        {asset.sourceText}
      </p>
    </div>
  );
}
